---
# vars file for python_app
instance_list:
  - webapp1
  - webapp2
  - db1

region: sgp1
image: ubuntu-22-04-x64
size: s-1vcpu-1gb
project: Ansible

db_name: employee_db
db_user: db_user
db_user_password: Passw0rd