- name: Install Python Flask dependency
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  with_items:
    - flask
    - flask-mysql

- name: Copy source code
  ansible.builtin.git:
    repo: 'https://github.com/mmumshad/simple-webapp.git'
    dest: /opt/simple-webapp

- name: Print command
  ansible.builtin.debug:
    msg: "MYSQL_DATABASE_HOST={{ hostvars[groups['db'][0]]['private_ip'] }} FLASK_APP=/opt/simple-webapp/app.py nohup flask run --host=0.0.0.0 --port=80 &"

- name: Start Web Server
  ansible.builtin.shell: "MYSQL_DATABASE_HOST={{ hostvars[groups['db'][0]]['private_ip'] }} FLASK_APP=/opt/simple-webapp/app.py nohup flask run --host=0.0.0.0 --port=80 &"
